services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: always
    depends_on:
      - postgres

volumes:
  postgres:
  redis:
